src/Entity/Record.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\RecordRepository")
 */
class Record
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="date")
     */
    private $releasedAt;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Artist", inversedBy="records")
     * @ORM\JoinColumn(nullable=false)
     */
    private $artist;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Label", inversedBy="records")
     */
    private $label;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Note", mappedBy="record", orphanRemoval=true, cascade={"persist"})
     * @ORM\OrderBy({"createdAt"="DESC"})
     */
    private $notes;

    public function __construct()
    {
        $this->notes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getReleasedAt(): ?\DateTimeInterface
    {
        return $this->releasedAt;
    }

    public function setReleasedAt(\DateTimeInterface $releasedAt): self
    {
        $this->releasedAt = $releasedAt;

        return $this;
    }

    public function getArtist(): ?Artist
    {
        return $this->artist;
    }

    public function setArtist(?Artist $artist): self
    {
        $this->artist = $artist;

        return $this;
    }

    public function getLabel(): ?Label
    {
        return $this->label;
    }

    public function setLabel(?Label $label): self
    {
        $this->label = $label;

        return $this;
    }

    /**
     * @return Collection|Note[]
     */
    public function getNotes(): Collection
    {
        return $this->notes;
    }

    public function addNote(Note $note): self
    {
        if (!$this->notes->contains($note)) {
            $this->notes[] = $note;
            $note->setRecord($this);
        }

        return $this;
    }

    public function removeNote(Note $note): self
    {
        if ($this->notes->contains($note)) {
            $this->notes->removeElement($note);
            // set the owning side to null (unless already changed)
            if ($note->getRecord() === $this) {
                $note->setRecord(null);
            }
        }

        return $this;
    }

    public function getAverageNote() : ?float
    {
        // Pas de note: null
        if ($this->notes->isEmpty()) {
            return null;
        }

        // Extraire les valeurs des notes
        $values = $this->notes->map(function (Note $note) {
            return $note->getValue();
        });

        // Somme des notes
        $sum = array_sum($values->getValues());
        // Moyenne
        $average = $sum / $this->notes->count();
        return $average;
    }
}

src/Controller/RecordController.php
<?php

namespace App\Controller;

use App\Entity\Note;
use App\Entity\Record;
use App\Form\NoteFormType;
use App\Repository\NoteRepository;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;

/**
 * @Route("/record", name="record_")
 */
class RecordController extends AbstractController
{
    /**
     * Exemple: /record/42
     * @Route("/{id}", name="page")
     */
    public function index(
        Record $record,
        Request $request,
        EntityManagerInterface $em,
        Security $security,
        NoteRepository $noteRepository
    ) {
        // Traiter le formulaire uniquement lorsque connecté
        if ($security->isGranted('ROLE_USER')) {
            // Rechercher une Note à modifier
            $note = $noteRepository->findOneBy([
                'record' => $record,
                'user' => $this->getUser()
            ]);

            // Pas de Note existante: initialisation
            if ($note === null) {
                $note = (new Note())
                    ->setRecord($record)
                    ->setUser($this->getUser())
                ;
            }

            $noteForm = $this->createForm(NoteFormType::class, $note);
            $noteForm->handleRequest($request);

            if ($noteForm->isSubmitted() && $noteForm->isValid()) {
                $note = $noteForm->getData();

                $em->persist($note);
                $em->flush();

                $this->addFlash('success', 'Note enregistrée');
            }
        }

        return $this->render('record/record_page.html.twig', [
            'record' => $record,
            'note_form' => isset($noteForm) ? $noteForm->createView() : null
        ]);
    }

    /**
     * @Route("/note-delete/{id}", name="delete_note")
     * @IsGranted("NOTE_DELETE", subject="note")
     */
    public function deleteNote(Note $note)
    {
        dd('Vous avez le droit de suppression de la note !');
    }
}

templates/record/record_page.html.twig
{% extends "_template.html.twig" %}

{% block title %}
    {{ record.title }}
{% endblock %}

{% block content %}
    <div class="section">
        <h2 class="title">
            Album: {{ record.title }}
            <span class="tag is-primary">
                {{ record.averageNote|number_format(2) }}
                /10
            </span>
        </h2>
        <small>Sorti le {{ record.releasedAt|date('d/m/Y') }}</small>
        <p>{{ record.description }}</p>

        <hr>
        <b>Artiste:</b>
        <a href="{{ path('artist_page', {id: record.artist.id}) }}">
            {{ record.artist.name }}
        </a>
        <br>

        {% if record.label %}
            <b>Label:</b>
            <a href="{{ path('label_page', {id: record.label.id}) }}">
                {{ record.label.name }}
            </a>
        {% else %}
            <p>Autoproduction</p>
        {% endif %}

        <hr>
        <h3 class="subtitle">
            Notes: {{ record.notes|length }}
        </h3>

        {% include 'includes/flash_message.html.twig' %}
        
        {# afficher le formulaire seulement si note_form n'est pas null #}
        {% if note_form is not null %}
            <div class="section">
                {{ form_start(note_form) }}
                    {{ form_row(note_form.value, {
                        label: 'Votre note'
                    }) }}

                    {{ form_row(note_form.comment, {
                        label: 'Commentaire (facultatif)'
                    }) }}

                    <button class="button is-success" type="submit">
                        Noter
                    </button>
                {{ form_end(note_form) }}
            </div>
        {% endif %}

        {% for note in record.notes %}
            {# @var note \App\Entity\Note #}
            <br>
            <div class="card">
                <div class="card-content">
                    <strong>
                        Note:
                        <span class="has-text-primary">{{ note.value }}/10</span>
                    </strong>
                    <br>
                    {{ note.comment }}
                    <hr>
                    <small>
                        {% if is_granted('NOTE_DELETE', note) %}
                            <a href="{{ path('record_delete_note', {id: note.id}) }}" class="button is-danger is-small">
                                <i class="far fa-times-circle"></i>&nbsp;
                                Supprimer
                            </a>
                        {% endif %}
                        
                        Par <b>{{ note.user.pseudo }}</b>
                        le <b>{{ note.createdAt|date('d/m/Y') }}</b>
                        à <b>{{ note.createdAt|date('H:i') }}</b>.
                    </small>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}